<a href="https://colab.research.google.com/github/sily3586/Repository_HM/blob/master/test/tensor_tutorial_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline 

In [0]:
from __future__ import print_function #future모듈에서 print함수를 가져옴 -> python2의 print와 python3의 print를 맞춰주는 과정.
import torch #torch모듈을 전부 가져옴.

In [3]:
x = torch.empty(5, 3) #초기화되지 않은 5x3행렬 x를 생성.
print(x)

tensor([[2.6311e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 2.1974e+23],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 6.9774e+22]])


In [4]:
x = torch.rand(5, 3) #0과 1사이의 값으로 랜덤하게 초기화된 5x3행렬 x를 생성.
print(x)

tensor([[0.1034, 0.4927, 0.4762],
        [0.1219, 0.9637, 0.2639],
        [0.9098, 0.6662, 0.9633],
        [0.8439, 0.7127, 0.9551],
        [0.1978, 0.7004, 0.2729]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long) #torch.long 데이터 타입을 가지며 0으로 채워진 5x3행렬 x를 생성.
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3]) #지정된 데이터로부터 직접 텐서를 생성.
print(x)

tensor([5.5000, 3.0000])


In [7]:
#혹은 기존의 텐서를 기반으로 같은 구조를 가진 텐서 생성. 이 방법은 사용자에 의해 새로운 값이 주어지지 않으면 입력 텐서의 속성(e.g. 데이터타입) 등이 재사용 됨.
x = x.new_ones(5, 3, dtype=torch.double)      # new_ones를 통해 5x3행렬이며 값이 1로 채워진 텐서를 torch.double 타입으로 생성
print(x)

x = torch.randn_like(x, dtype=torch.float)    #torch.randn_like() 함수를 통해 0과 1사이의 랜덤한 값으로 채워지며 x와 같은 크기인 5x3 크기의 텐서를 구성하되 데이터 타입은 torch.float으로 한 행렬 생성
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.2175,  2.6860,  0.1637],
        [ 0.6697, -1.1266,  0.1889],
        [ 1.6147, -2.3636,  0.6136],
        [ 1.3629, -0.5042,  0.1857],
        [ 0.7782,  0.7399, -0.8643]])


In [8]:
print(x.size())#생성한 텐서의 사이즈를 확인

torch.Size([5, 3])


In [9]:
#텐서의 연산
#방법1
y = torch.rand(5, 3) #0과 1사이의 랜덤한 값으로 채워진 5x3행렬 y 생성
print(x + y) #텐서 x와 y를 +연산.

tensor([[ 1.5285,  3.1756,  0.5804],
        [ 1.5869, -0.5682,  0.4341],
        [ 2.4586, -2.1497,  1.0155],
        [ 2.0233,  0.0298,  0.6318],
        [ 0.9538,  1.2841,  0.0337]])


In [10]:
#방법2
print(torch.add(x, y)) #torch.add()함수를 사용하여 텐서의 +연산.

tensor([[ 1.5285,  3.1756,  0.5804],
        [ 1.5869, -0.5682,  0.4341],
        [ 2.4586, -2.1497,  1.0155],
        [ 2.0233,  0.0298,  0.6318],
        [ 0.9538,  1.2841,  0.0337]])


In [11]:
#방법3 : 파라미터로 결과가 저장되는 output tensor 이용
result = torch.empty(5, 3) #torch.empty()를 사용하여 5x3의 초기화되지 않은 값이 채워진 tensor를 생성
torch.add(x, y, out=result) #torch.add()함수를 사용하여 x, y를 더하되 매개변수 out에 result를 넘겨주어 출력값을 result에 대입.
print(result) #result를 출력

tensor([[ 1.5285,  3.1756,  0.5804],
        [ 1.5869, -0.5682,  0.4341],
        [ 2.4586, -2.1497,  1.0155],
        [ 2.0233,  0.0298,  0.6318],
        [ 0.9538,  1.2841,  0.0337]])


In [12]:
#방법4 : 제자리 연산
y.add_(x) #y에 x를 더하여 y저장
print(y)
#텐서를 제자리에서 변경하는 연산은 postfix(연산자를 피연산자 뒤쪽에 표시)로 표기.
#예를 들어 x.copy_(y)와 x.t_()는 x를 변경

tensor([[ 1.5285,  3.1756,  0.5804],
        [ 1.5869, -0.5682,  0.4341],
        [ 2.4586, -2.1497,  1.0155],
        [ 2.0233,  0.0298,  0.6318],
        [ 0.9538,  1.2841,  0.0337]])


In [13]:
#NumPy와 같은 표준 인덱싱을 사용할 수 있음.
print(x[1:3, 0]) #텐서 x의 두번째 열의 두번째 행과 세번째 행 출력.

tensor([0.6697, 1.6147])


In [14]:
#텐서의 size나 shape을 바꾸려면 torch.view를 사용
x = torch.randn(4, 4) #4x4의 랜덤한 행렬 생성.
y = x.view(16) #tensor x의 크기를 16으로 변환한 값을 y에 저장
z = x.view(-1, 8)  #tensor x의 크기를 -1x8로 변환하여 z에 저장. 이때 '-1'의 의미는 현재 값을 다른 값에 의해 계산하겠다는 의미.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
#한개의 요소를 가지는 텐서가 있다면, item()함수를 사용하여 python에서의 숫자 데이터처럼 값을 얻을 수 있음.
x = torch.randn(1)
print(x)
print(x.item()) #tensor x의 요소를 python에서 처럼 출력

tensor([1.7961])
1.7960928678512573


In [16]:
#NumPy Bridge(NumPy 변환)
#torch tensor에서 numpy 배열 또는 그 반대로 변환하는 것은 어렵지 않음.
#둘은 근본적으로 메모리 위치를 공유하기 때문에 하나를 변경하면 다른 하나도 변경됨.

#torch tensor를 NumPy배열로 변경하기
a = torch.ones(5) #torch.ones()를 사용하여 크기가 5이며 값이 1인 tensor a를 생성
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy() #a를 numpy로 변환하여 b에 저장
print(b)

[1. 1. 1. 1. 1.]


In [18]:
#numpy배열의 값이 변하는 과정
a.add_(1) #add_() 함수를 사용하여 a에 1을 더하여 a에 저장
print(a) #a를 출력
print(b) #b를 출력. NumPy Bridge로 인해 numpy b 의 값이 바뀐 것을 확인

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
#NumPy배열을 torch tensor로 변경하기
#Numpy배열이 torch tensor로 자동으로 바뀌는 과정
import numpy as np #numpy를 np로 import
a = np.ones(5) #numpy 타입의 사이즈가 5, 값이 1인 배열을 생성
b = torch.from_numpy(a) #torch.from_numpy() 함수를 통해 이 numpy 타입의 배열 a를 tensor로 읽어들여 b에 저장
np.add(a, 1, out=a) #np.add() 함수를 통해 a에 1를 더하고 out 매개변수에 a를 넘겨줌으로써 출력값을 a에 저장
print(a) #a를 출력
print(b) #b를 출력

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
#tensor는 .to 메서드를 사용하여 cuda를 지원하는 디바이스로 옮길 수 있음.
# 이 셀이 쿠다를 지원하는 경우에만 실행되도록 함.
# GPU의 안팎으로 tensor를 이동하기 위해 torch.device 객체를 사용
if torch.cuda.is_available(): #cuda를 지원한다면
    device = torch.device("cuda")          
    y = torch.ones_like(x, device=device)  #GPU에 직접 텐서 생성
    x = x.to(device)                       #또는 ``.to("cuda")``사용
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 데이터 타입도 바꿀 수 있음.

tensor([2.7961], device='cuda:0')
tensor([2.7961], dtype=torch.float64)
